"""add max_size column to lobby

Revision ID: 1855ef619382
Revises: 37c5714b96e0
Create Date: 2026-05-09 15:47:31.568478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1855ef619382'
down_revision: Union[str, Sequence[str], None] = '37c5714b96e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lobby', sa.Column('max_size', sa.Integer(), nullable=False, default=8))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lobby', 'max_size')
    # ### end Alembic commands ###
