"""add max_size column to lobby

Revision ID: 1855ef619382
Revises: 37c5714b96e0
Create Date: 2026-05-09 15:47:31.568478

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1855ef619382"
down_revision: str | Sequence[str] | None = "37c5714b96e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lobby", sa.Column("max_size", sa.Integer(), nullable=False, default=8)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lobby", "max_size")
    # ### end Alembic commands ###
