"""add private lobbies

Revision ID: 1df3a6141c0b
Revises: fbb59b9e7668
Create Date: 2026-05-11 13:54:11.582205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1df3a6141c0b'
down_revision: Union[str, Sequence[str], None] = 'fbb59b9e7668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lobby', sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lobby', 'secret')
    # ### end Alembic commands ###
