"""change lobby ids to uuids

Revision ID: fbb59b9e7668
Revises: 1855ef619382
Create Date: 2026-05-09 16:32:51.319269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fbb59b9e7668'
down_revision: Union[str, Sequence[str], None] = '1855ef619382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lobby") as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            type_=sa.Uuid(),
            existing_nullable=False
        )
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column(
            "lobby_id",
            existing_type=sa.INTEGER(),
            type_=sa.Uuid(),
            existing_nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column(
            "lobby_id",
            existing_type=sa.Uuid(),
            type_=sa.INTEGER(),
            existing_nullable=True
        )
    with op.batch_alter_table("lobby") as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.Uuid(),
            type_=sa.INTEGER(),
            existing_nullable=False
        )
    # ### end Alembic commands ###
