# Some global defaults
worker_processes auto;
pid /run/nginx.pid;
# where to place the error logs - useful to check if getting gateway errors
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

# Runtime async options - scale to more for production depending on expected load
events {
    worker_connections 768;
    # multi_accept on;
}

http {

    ##
    # Basic Settings
    ##

    server {

        listen 5000; # server listens on port 5000

        # serve sw.js from the service worker code, needed for web
        # browser security purposes or else need to set Service-Worker-Allowed
        # header to "/". Read more at:
        # https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Service-Worker-Allowed
        location = /sw.js {
            alias /app/dist/sw.worker.js;
        }

        # where to serve the frontend from. enables autoindex as well with json
        # format for easy processing of the static content (needed so that service
        # worker works)
        location / {
            root /app;
            autoindex on;
            autoindex_format json;
        }

        # proxy requests to the api endpoint to the backend server. podman
        # deals with proxying for us, and exposes the backend only to the
        # frontend container
        location /api/ {
            proxy_pass http://backend:9000/;
        }
    }

    # include the default mime types
    include /etc/nginx/mime.types;
}
